# Generated by Django 4.1.7 on 2023-02-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
