# Generated by Django 4.1.6 on 2023-02-07 06:12

from django.db import migrations, models
import myApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to=myApp.models.file_path)),
            ],
        ),
    ]
