# Generated by Django 4.1.6 on 2023-02-10 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_filehandler_upload_date_filehandler_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=100)),
                ('journal_name', models.CharField(max_length=100)),
                ('nashr_sanasi', models.DateField()),
                ('bob', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=100)),
                ('sahifalar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=100)),
                ('nashr_sanasi', models.DateField()),
                ('nashriyot_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('dgunomer', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=100)),
                ('yunalish', models.CharField(max_length=100)),
            ],
        ),
    ]
