# Generated by Django 4.1.6 on 2023-02-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_filehandler_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='dgunomer',
            field=models.IntegerField(),
        ),
    ]
