# Generated by Django 4.1.7 on 2023-02-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_maqolabaza_dissertationbaza_dgubaza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='data',
            new_name='date',
        ),
    ]
