# Generated by Django 4.1.7 on 2023-02-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_dgubaza_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbaza',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dissertationbaza',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maqolabaza',
            name='user',
        ),
    ]
