# Generated by Django 4.1.7 on 2023-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_alter_bookbaza_user_alter_dgubaza_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbaza',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dgubaza',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dissertationbaza',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filehandler',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maqolabaza',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
