# Generated by Django 4.1.7 on 2023-02-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_bookbaza_upload_date_alter_dgubaza_upload_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileHandler',
        ),
    ]
