# Generated by Django 4.1.7 on 2023-03-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_rename_muallif_article_maq_muallif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqolabaza',
            name='maq_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
    ]
