# Generated by Django 4.1.7 on 2023-03-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_maqolabaza_maq_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolabaza',
            name='maq_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
    ]
