# Generated by Django 4.1.7 on 2023-03-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0022_alter_maqolabaza_maq_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqolabaza',
            old_name='maq_name',
            new_name='maqola_name',
        ),
        migrations.RemoveField(
            model_name='maqolabaza',
            name='user',
        ),
    ]
