# Generated by Django 4.1.7 on 2023-03-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0023_rename_maq_name_maqolabaza_maqola_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolabaza',
            name='maqola_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
    ]
