# Generated by Django 4.1.7 on 2023-03-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_alter_maqolabaza_maqola_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookbaza',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dgubaza',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dissertationbaza',
            name='user',
        ),
        migrations.AddField(
            model_name='bookbaza',
            name='kitob_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
        migrations.AddField(
            model_name='dgubaza',
            name='dgu_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
        migrations.AddField(
            model_name='dissertationbaza',
            name='disser_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.dissertation'),
        ),
    ]
