# Generated by Django 4.1.7 on 2023-03-10 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_remove_bookbaza_user_remove_dgubaza_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='bob',
        ),
        migrations.RemoveField(
            model_name='article',
            name='number',
        ),
        migrations.RemoveField(
            model_name='book',
            name='nashriyot_name',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='yunalish',
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='volum',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='application_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='dis_nashr_sanasi',
            field=models.DateField(default=datetime.datetime(2023, 3, 10, 14, 40, 31, 692918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='institut',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='dgunomer',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
