# Generated by Django 4.1.7 on 2023-03-11 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0031_remove_article_bob_remove_article_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='dis_nashr_sanasi',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
