# Generated by Django 4.1.7 on 2023-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_alter_dissertation_dis_nashr_sanasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='journal_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='maq_muallif',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='maq_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_muallif',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cer_muallif',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cer_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='dis_muallif',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='dis_name',
            field=models.CharField(max_length=250),
        ),
    ]
