# Generated by Django 4.1.7 on 2023-03-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_alter_article_journal_name_alter_article_maq_muallif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgubaza',
            name='dgu_name',
            field=models.ForeignKey(default='Maqola mavjud emas', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
        migrations.AlterField(
            model_name='maqolabaza',
            name='maqola_name',
            field=models.ForeignKey(default='Maqola mavjud emas', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
    ]
