# Generated by Django 4.1.7 on 2023-03-13 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0036_alter_dgubaza_dgu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbaza',
            name='kitob_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.book'),
        ),
    ]
