# Generated by Django 4.1.7 on 2023-03-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0039_alter_article_maq_nashr_sanasi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='maq_nashr_sanasi',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_nashr_sanasi',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.TimeField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='dis_nashr_sanasi',
            field=models.TimeField(max_length=200),
        ),
    ]
