# Generated by Django 4.1.7 on 2023-10-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0043_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='create_ad',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='description',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='ordernumber',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='status',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='title',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='update_ad',
        ),
        migrations.AddField(
            model_name='archives',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
