# Generated by Django 4.1.7 on 2023-10-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0044_remove_archives_create_ad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archives',
        ),
    ]
