# Generated by Django 4.1.7 on 2023-10-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0045_delete_archives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolabaza',
            name='maqola_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.article'),
        ),
    ]
