# Generated by Django 4.1.7 on 2023-10-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0046_alter_maqolabaza_maqola_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
