# Generated by Django 4.1.7 on 2023-10-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0047_alter_article_abstract_alter_article_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookbaza',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dgubaza',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='dissertationbaza',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='maqolabaza',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
