# Generated by Django 4.1.7 on 2023-10-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0049_alter_maqolabaza_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqolabaza',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
